os: linux
dist: xenial
language: node_js
node_js:
  - 10
  - 12
  - 14
before_install:
  - npm install -g npm@latest
before_script:
  - |
      if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md)|(.png)|(.ai)|(.svg)|(.jpg)|(.pdf)|^(LICENSE)|^(docs)|^(media)'
      then
        echo "Only doc files were updated, not running the CI."
        exit
      fi
  - npm install -g gulp-cli
after_success:
  - ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/codecov --pipe
script:
  - npm test
